# Generated by Django 6.0.3 on 2026-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('affiche', models.ImageField(upload_to='realisations/affiches/')),
                ('video', models.FileField(upload_to='realisations/videos/')),
                ('genre', models.CharField(max_length=100)),
                ('duree', models.IntegerField()),
                ('date_sortie', models.DateField()),
                ('est_publie', models.BooleanField(default=False)),
                ('utilise_pour_financement', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
