# Generated by Django 6.0.3 on 2026-03-18 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realisation',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Réalisation', 'verbose_name_plural': 'Réalisations'},
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='description',
        ),
        migrations.AddField(
            model_name='realisation',
            name='annee_production',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de production'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='bande_annonce',
            field=models.FileField(blank=True, help_text='Video trailer (MP4, max 100 Mo)', null=True, upload_to='realisations/bandes_annonces/', verbose_name='Bande-annonce'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='casting',
            field=models.TextField(blank=True, help_text='Liste des acteurs principaux', verbose_name='Casting / Acteurs'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='langue_originale',
            field=models.CharField(blank=True, max_length=100, verbose_name='Langue originale'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='musique',
            field=models.CharField(blank=True, max_length=200, verbose_name='Musique / Compositeur'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='pays',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays de production'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='pitch',
            field=models.CharField(blank=True, help_text="Courte description pour attirer l'attention (max 500 caractères)", max_length=500, verbose_name='Pitch / Accroche'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='realisateur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Réalisateur'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='scenario',
            field=models.TextField(blank=True, verbose_name='Scénario / Scénographie'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='synopsis',
            field=models.TextField(blank=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='affiche',
            field=models.ImageField(upload_to='realisations/affiches/', verbose_name='Affiche du film'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='duree',
            field=models.IntegerField(verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='realisations/videos/', verbose_name='Film complet'),
        ),
    ]
