# Generated by Django 6.0.3 on 2026-03-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0003_add_fiche_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='est_brouillon',
            field=models.BooleanField(default=True, verbose_name='Brouillon'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='est_soumis',
            field=models.BooleanField(default=False, verbose_name='Soumis pour validation'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='message_admin',
            field=models.TextField(blank=True, verbose_name="Message de l'administrateur"),
        ),
    ]
