# Generated by Django 6.0.3 on 2026-03-24 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0004_realisation_est_brouillon_realisation_est_soumis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='acteurs_invites',
            field=models.ManyToManyField(blank=True, related_name='realisations_acteur', to=settings.AUTH_USER_MODEL, verbose_name='Acteurs invités'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='auteurs_invites',
            field=models.ManyToManyField(blank=True, related_name='realisations_collab', to=settings.AUTH_USER_MODEL, verbose_name='Auteurs invités'),
        ),
    ]
