# Generated by Django 6.0.3 on 2026-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('auteur', 'Auteur'), ('acteur', 'Acteur'), ('producteur', 'Producteur'), ('fan', 'Fan')], default='fan', max_length=20),
        ),
    ]
