# Generated by Django 6.0.3 on 2026-03-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_ministere', models.CharField(max_length=100, verbose_name='Matricule du Ministère de la Culture')),
                ('type_piece_identite', models.CharField(choices=[('cni', 'CNI'), ('passport', 'Passeport')], default='cni', max_length=20, verbose_name="Type de pièce d'identité")),
                ('document_cni_passport', models.FileField(help_text='PDF ou image (max 7 Mo)', upload_to='documents/cni_passport/', verbose_name='CNI ou Passeport')),
                ('document_registre_commerce', models.FileField(help_text='PDF ou image (max 7 Mo)', upload_to='documents/registre_commerce/', verbose_name='Registre de Commerce')),
                ('document_rib', models.FileField(help_text='PDF ou image (max 7 Mo)', upload_to='documents/rib/', verbose_name="RIB de l'entreprise")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de vérification'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True, verbose_name="Commentaire de l'administrateur")),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents_professionnels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
