# Generated by Django 6.0.3 on 2026-03-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_documentprofessionnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentprofessionnel',
            name='document_rib',
        ),
    ]
