# Generated by Django 6.0.3 on 2026-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_contribution', models.DateTimeField(auto_now_add=True)),
                ('moyen_paiement', models.CharField(max_length=50)),
            ],
        ),
    ]
