# Generated by Django 6.0.3 on 2026-03-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communaute', '0001_initial'),
        ('realisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realisations.realisation'),
        ),
    ]
