# Generated by Django 6.0.3 on 2026-03-24 14:09

import communaute.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communaute', '0003_initial'),
        ('projets', '0006_add_invitation'),
        ('realisations', '0005_add_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=communaute.models.generate_invitation_code, max_length=10, unique=True)),
                ('type_invitation', models.CharField(choices=[('auteur', 'Auteur'), ('auteur_projet', 'Auteur (Projet)'), ('auteur_realisation', 'Auteur (Film)'), ('acteur', 'Acteur')], max_length=20)),
                ('email_invite', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('expiree', 'Expirée'), ('revokee', 'Révoquée')], default='en_attente', max_length=20)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL)),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_recues', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to='projets.projet')),
                ('realisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to='realisations.realisation')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
