# Generated by Django 6.0.3 on 2026-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('pre_affiche', models.ImageField(upload_to='projets/pre_affiches/')),
                ('budget_objectif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('financement', 'En financement'), ('finance', 'Financé'), ('annule', 'Annulé')], default='attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
