# Generated by Django 6.0.3 on 2026-03-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_initial'),
        ('realisations', '0003_add_fiche_technique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début du financement'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin du financement'),
        ),
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du projet', verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='projet',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('drame', 'Drame'), ('comedie', 'Comédie'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('science-fiction', 'Science-Fiction'), ('documentaire', 'Documentaire'), ('animation', 'Animation'), ('aventure', 'Aventure'), ('horreur', 'Horreur')], max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projet',
            name='pre_affiche',
            field=models.ImageField(upload_to='projets/pre_affiches/', verbose_name='Pré-affiche'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='realisation_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projet_financement', to='realisations.realisation'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='synopsis',
            field=models.TextField(help_text='Résumé court du projet', verbose_name='Synopsis'),
        ),
    ]
