# Generated by Django 6.0.3 on 2026-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_projet_est_brouillon_projet_est_soumis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='nom_banque',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='projet',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte'),
        ),
        migrations.AddField(
            model_name='projet',
            name='rib_document',
            field=models.FileField(blank=True, null=True, upload_to='projets/ribs/', verbose_name="Relevé d'identité bancaire (RIB)"),
        ),
        migrations.AddField(
            model_name='projet',
            name='titulaire_compte',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titulaire du compte'),
        ),
    ]
