# Generated by Django 6.0.3 on 2026-03-24 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_projet_nom_banque_projet_numero_compte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='acteurs_invites',
            field=models.ManyToManyField(blank=True, related_name='projets_acteur', to=settings.AUTH_USER_MODEL, verbose_name='Acteurs invités'),
        ),
        migrations.AddField(
            model_name='projet',
            name='auteurs_invites',
            field=models.ManyToManyField(blank=True, related_name='projets_collab', to=settings.AUTH_USER_MODEL, verbose_name='Auteurs invités'),
        ),
    ]
